### ISSUE TITLE
cant start training

### ISSUE THREAD

**Issue by AmeenAli** [yukimasano/linear-probes#1]
Traceback (most recent call last):
  File "eval_linear_probes.py", line 295, in <module>
    model = model_with_probes(model_path=args.modelpath)
  File "eval_linear_probes.py", line 88, in model_with_probes
    state_dict = torch.load(model_path)['state_dict']
  File "/home/ameenali/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ameenali/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ameenali/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '.ckpt400.pth'
where can i find the checkpoint file?

**Comment by yukimasano** [comment]
Hey there. 
this repo only provides you with the evaluation code. But you can for example download an AlexNet model from this repo: https://github.com/yukimasano/self-label (there might be some adjusting of weight-names needed)
